sudo: false

language: python

python:
  - "3.5"
  - "3.6"

install: pip install tox-travis coveralls

script: tox

after_success: coveralls

notifications:
  irc:
    channels:
      - "chat.freenode.net#asphalt"
    on_success: change
    on_failure: change
    use_notice: true
    skip_join: true

deploy:
  provider: pypi
  user: agronholm
  password:
    secure: IgSfhS6d2kVsEDacq4GH470hbTwHRaQ+9V8o46+Mi+3pq6vwSH9U5jWqQ5u2n/wYAzEfYSS2KwxkLvh4f/lpu3hk9dOqG8b6eIcwzVe+eV9mmNETt+9JVjAV8VdEZPoWDvKoZS+N6ywfFLU4krxPZ4Te5nLjADFrAr3D66MQWqNAYByjZHJyemxPte5QHDo8CFtLtDZUNxyTHnAJCWSq2jASPhZ3maoyXMc+TOjS3xnp5UmbAD+TtwXfFucamK/cb6/jH8dW0UVV990oMnbF+ntjrRCPC5a54HFqiM5kQxKw1e1wgsmYcY8+gCg+sEff+D3CRFj7x+3TufgaATUCRhQ+tXjpwON2ZkkINg7CZc/i5nCQCp8oWVESgOewixoLdODL0rjZ9GzhqwYI0JV/MqSMScqo6vM/RFKQzYYG7PzZzMxXuq+UGEnVQYvwM7DR7K76etg+HCEuQHeYNHqSlg+Yn9axRg+piiXayR+knY5iOYB49ziiKXgqxnGv1juTEZrfH5Bl+QZM0OXjD7ev6vj2NpYuxPSf13aBBYWo2/yqbfu+hYbpttMA4Jmjk391F2UxQuLC9wCV8/FjIIXtBJG2TFjYYejRQ4o0FV1eJaDzJpPbSlxQeOLlE/FIHSmvcKKQBOmIK5/HUL34d5hyazuI3OGyo/FfAj++JwA24gA=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "3.5"
    repo: asphalt-framework/asphalt-py4j
